repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.59.1
    hooks:
    -   id: golangci-lint
-   repo: local
    hooks:
    -   id: unit-tests
        name: Run unit tests
        entry: make test
        language: system
        pass_filenames: false
    -   id: coverage-report
        name: Generate coverage report
        entry: make coverage
        language: system
        pass_filenames: false
        verbose: true
