# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Install graphics drivers
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache-dependency-path: go.sum
    - name: Install dependencies
      run: |
        go get .
        go install github.com/hexira/go-ignore-cov@v0.3.0

    - name: Build
      run: go build -v ./...

    - name: Run test and output coverage
      run: |
        go test -coverprofile coverage.out -covermode count -coverpkg=./... -v ./... 
        go-ignore-cov --file coverage.out
        go tool cover -func=coverage.out

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
